spring:
  application:
    name: spring security 01
  thymeleaf:
    cache: true
  security:
    user:
      name: test-user
      password: user123
      roles: USER
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      path: /h2-console
      enabled: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
  jpa:
    database: h2
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:file:./database/spring_security;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  sql:
    init:
      platform: h2
      mode: always
      schema-locations: classpath:sql/schema_new.sql, classpath:org/springframework/session/jdbc/schema-h2.sql
      data-locations: classpath:sql/data_new.sql
      encoding: UTF-8
server:
  port: 443
  ssl:
    enabled: true
    key-alias: prgrms_keystore
    key-store: classpath:prgrms_keystore.p12
    key-store-password: prgrms123
    key-password: prgrms123
    trust-store: classpath:prgrms_truststore.p12
    trust-store-password: prgrms123